In [ ]:
import pandas as pd
df = pd.read_csv("merge_sum3.csv")
df.head()

    季度   縣市    地區    種類   款式     進貨總金額
0  第一季  南投縣  一般縣市    中性  一般款  1185.975
1  第一季  南投縣  一般縣市    中性  自動扣   698.250
2  第一季  南投縣  一般縣市    中性   針棒  2716.350
3  第一季  南投縣  一般縣市  特定性別  一般款  1114.050
4  第一季  南投縣  一般縣市  特定性別  自動扣   837.900

In [ ]:
df.rename(columns = {"種類":"品項定位"}, inplace = True)
df.rename(columns = {"進貨總金額":"銷售總金額"}, inplace = True)
df.set_index("季度", inplace=True)
df.head()

      縣市    地區  品項定位   款式     銷售總金額
季度
第一季  南投縣  一般縣市    中性  一般款  1185.975
第一季  南投縣  一般縣市    中性  自動扣   698.250
第一季  南投縣  一般縣市    中性   針棒  2716.350
第一季  南投縣  一般縣市  特定性別  一般款  1114.050
第一季  南投縣  一般縣市  特定性別  自動扣   837.900

In [ ]:
from google.colab import drive
drive.mount("/content/drive") # 連線到雲端硬碟
first_url = "/content/drive/MyDrive/暫存/"
df.to_csv(first_url + "final_result.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [36]:
import pandas as pd
data = pd.read_csv("final_result.csv")
data.head()

    季度   縣市    地區  品項定位   款式     銷售總金額
0  第一季  南投縣  一般縣市    中性  一般款  1185.975
1  第一季  南投縣  一般縣市    中性  自動扣   698.250
2  第一季  南投縣  一般縣市    中性   針棒  2716.350
3  第一季  南投縣  一般縣市  特定性別  一般款  1114.050
4  第一季  南投縣  一般縣市  特定性別  自動扣   837.900

In [47]:
import random
general_cities = data[data['地區'] == '一般縣市']['縣市'].unique()
random_cities = random.sample(list(general_cities), 6)
random_cities

['台東縣', '屏東縣', '嘉義縣', '苗栗縣', '澎湖縣', '宜蘭縣']

In [49]:
filtered_df = data[(data['地區'] == '直轄市') | (data['縣市'].isin(random_cities))]
filtered_df

      季度   縣市    地區  品項定位   款式      銷售總金額
6    第一季  台中市   直轄市    中性  一般款   8847.825
7    第一季  台中市   直轄市    中性  自動扣   7945.875
8    第一季  台中市   直轄市    中性   針棒  11283.300
9    第一季  台中市   直轄市  特定性別  一般款  10446.450
10   第一季  台中市   直轄市  特定性別  自動扣   6976.074
..   ...  ...   ...   ...  ...        ...
472  第四季  苗栗縣  一般縣市  特定性別  自動扣      0.000
474  第一季  澎湖縣  一般縣市  特定性別  自動扣      0.000
477  第二季  澎湖縣  一般縣市    中性  一般款      0.000
478  第三季  台東縣  一般縣市  特定性別  一般款      0.000
479  第一季  澎湖縣  一般縣市  特定性別  一般款      0.000

[288 rows x 6 columns]

In [25]:
def sample_group(group):
    return group.sample(n=min(6, len(group)), random_state=10)

In [ ]:
data['組合'] = data['季度'] + "_" + data['地區'] + "_" + data['品項定位'] + "_" + data['款式']
data.head()

    季度   縣市    地區  品項定位   款式     銷售總金額                 組合
0  第一季  南投縣  一般縣市    中性  一般款  1185.975    第一季_一般縣市_中性_一般款
1  第一季  南投縣  一般縣市    中性  自動扣   698.250    第一季_一般縣市_中性_自動扣
2  第一季  南投縣  一般縣市    中性   針棒  2716.350     第一季_一般縣市_中性_針棒
3  第一季  南投縣  一般縣市  特定性別  一般款  1114.050  第一季_一般縣市_特定性別_一般款
4  第一季  南投縣  一般縣市  特定性別  自動扣   837.900  第一季_一般縣市_特定性別_自動扣

In [26]:
result = data.groupby('組合', group_keys=False).apply(sample_group)
result.set_index("季度", inplace=True)
del result["組合"]
result

<ipython-input-26-c11e87c87a7e>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = data.groupby('組合', group_keys=False).apply(sample_group)

      縣市    地區  品項定位   款式      銷售總金額
季度
第一季  基隆市  一般縣市    中性  一般款    627.375
第一季  新竹市  一般縣市    中性  一般款   1393.875
第一季  金門縣  一般縣市    中性  一般款    139.125
第一季  彰化縣  一般縣市    中性  一般款   1811.775
第一季  新竹縣  一般縣市    中性  一般款   2511.075
..   ...   ...   ...  ...        ...
第四季  高雄市   直轄市  特定性別   針棒  12103.875
第四季  台中市   直轄市  特定性別   針棒  10851.750
第四季  新北市   直轄市  特定性別   針棒   9321.375
第四季  桃園市   直轄市  特定性別   針棒   8208.375
第四季  台北市   直轄市  特定性別   針棒   6538.875

[288 rows x 5 columns]

In [27]:
result[result.地區=="一般縣市"]["縣市"].value_counts()

縣市
新竹市    24
新竹縣    24
基隆市    23
嘉義縣    20
彰化縣    19
金門縣    11
雲林縣    11
澎湖縣     6
宜蘭縣     5
苗栗縣     1
Name: count, dtype: int64

In [50]:
from google.colab import drive
drive.mount("/content/drive") # 連線到雲端硬碟
first_url = "/content/drive/MyDrive/暫存/"
filtered_df.to_csv(first_url + "4.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).